// Code generated by goctl. DO NOT EDIT.
// Source: mixinsrv.proto

package mixinsrv

import (
	"context"

	"github.com/lixvyang/rebetxin-one/service/mixinsrv/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendBtnGroupReq  = pb.SendBtnGroupReq
	SendBtnGroupResp = pb.SendBtnGroupResp
	SendCardReq      = pb.SendCardReq
	SendCardResp     = pb.SendCardResp
	SendMessageReq   = pb.SendMessageReq
	SendMessageResp  = pb.SendMessageResp
	SendTransferReq  = pb.SendTransferReq
	SendTransferResp = pb.SendTransferResp

	Mixinsrv interface {
		// -----------------------mixinsrv-----------------------
		SendTransfer(ctx context.Context, in *SendTransferReq, opts ...grpc.CallOption) (*SendTransferResp, error)
		SendCard(ctx context.Context, in *SendCardReq, opts ...grpc.CallOption) (*SendCardResp, error)
		SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
		SendBtnGroup(ctx context.Context, in *SendBtnGroupReq, opts ...grpc.CallOption) (*SendBtnGroupResp, error)
	}

	defaultMixinsrv struct {
		cli zrpc.Client
	}
)

func NewMixinsrv(cli zrpc.Client) Mixinsrv {
	return &defaultMixinsrv{
		cli: cli,
	}
}

// -----------------------mixinsrv-----------------------
func (m *defaultMixinsrv) SendTransfer(ctx context.Context, in *SendTransferReq, opts ...grpc.CallOption) (*SendTransferResp, error) {
	client := pb.NewMixinsrvClient(m.cli.Conn())
	return client.SendTransfer(ctx, in, opts...)
}

func (m *defaultMixinsrv) SendCard(ctx context.Context, in *SendCardReq, opts ...grpc.CallOption) (*SendCardResp, error) {
	client := pb.NewMixinsrvClient(m.cli.Conn())
	return client.SendCard(ctx, in, opts...)
}

func (m *defaultMixinsrv) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	client := pb.NewMixinsrvClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

func (m *defaultMixinsrv) SendBtnGroup(ctx context.Context, in *SendBtnGroupReq, opts ...grpc.CallOption) (*SendBtnGroupResp, error) {
	client := pb.NewMixinsrvClient(m.cli.Conn())
	return client.SendBtnGroup(ctx, in, opts...)
}
