// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: mixinsrv.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------
// Messages
// ------------------------------------
type SendTransferReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpponentId string `protobuf:"bytes,1,opt,name=opponent_id,json=opponentId,proto3" json:"opponent_id,omitempty"`
	AssetId    string `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Amount     string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Memo       string `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (x *SendTransferReq) Reset() {
	*x = SendTransferReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mixinsrv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransferReq) ProtoMessage() {}

func (x *SendTransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_mixinsrv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransferReq.ProtoReflect.Descriptor instead.
func (*SendTransferReq) Descriptor() ([]byte, []int) {
	return file_mixinsrv_proto_rawDescGZIP(), []int{0}
}

func (x *SendTransferReq) GetOpponentId() string {
	if x != nil {
		return x.OpponentId
	}
	return ""
}

func (x *SendTransferReq) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *SendTransferReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SendTransferReq) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

type SendTransferResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendTransferResp) Reset() {
	*x = SendTransferResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mixinsrv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTransferResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransferResp) ProtoMessage() {}

func (x *SendTransferResp) ProtoReflect() protoreflect.Message {
	mi := &file_mixinsrv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransferResp.ProtoReflect.Descriptor instead.
func (*SendTransferResp) Descriptor() ([]byte, []int) {
	return file_mixinsrv_proto_rawDescGZIP(), []int{1}
}

type SendMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content   string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ReceiptId string `protobuf:"bytes,2,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
}

func (x *SendMessageReq) Reset() {
	*x = SendMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mixinsrv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReq) ProtoMessage() {}

func (x *SendMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_mixinsrv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReq.ProtoReflect.Descriptor instead.
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return file_mixinsrv_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageReq) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

type SendMessageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendMessageResp) Reset() {
	*x = SendMessageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mixinsrv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResp) ProtoMessage() {}

func (x *SendMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_mixinsrv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResp.ProtoReflect.Descriptor instead.
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return file_mixinsrv_proto_rawDescGZIP(), []int{3}
}

type SendCardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tid       string `protobuf:"bytes,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Intro     string `protobuf:"bytes,3,opt,name=intro,proto3" json:"intro,omitempty"`
	IconUrl   string `protobuf:"bytes,4,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	ReceiptId string `protobuf:"bytes,5,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
}

func (x *SendCardReq) Reset() {
	*x = SendCardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mixinsrv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCardReq) ProtoMessage() {}

func (x *SendCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_mixinsrv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCardReq.ProtoReflect.Descriptor instead.
func (*SendCardReq) Descriptor() ([]byte, []int) {
	return file_mixinsrv_proto_rawDescGZIP(), []int{4}
}

func (x *SendCardReq) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *SendCardReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendCardReq) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

func (x *SendCardReq) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *SendCardReq) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

type SendCardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendCardResp) Reset() {
	*x = SendCardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mixinsrv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCardResp) ProtoMessage() {}

func (x *SendCardResp) ProtoReflect() protoreflect.Message {
	mi := &file_mixinsrv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCardResp.ProtoReflect.Descriptor instead.
func (*SendCardResp) Descriptor() ([]byte, []int) {
	return file_mixinsrv_proto_rawDescGZIP(), []int{5}
}

type SendBtnGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tid       string `protobuf:"bytes,1,opt,name=tid,proto3" json:"tid,omitempty"`
	AssetId   string `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	ReceiptId string `protobuf:"bytes,3,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
}

func (x *SendBtnGroupReq) Reset() {
	*x = SendBtnGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mixinsrv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBtnGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBtnGroupReq) ProtoMessage() {}

func (x *SendBtnGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_mixinsrv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBtnGroupReq.ProtoReflect.Descriptor instead.
func (*SendBtnGroupReq) Descriptor() ([]byte, []int) {
	return file_mixinsrv_proto_rawDescGZIP(), []int{6}
}

func (x *SendBtnGroupReq) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *SendBtnGroupReq) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *SendBtnGroupReq) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

type SendBtnGroupResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendBtnGroupResp) Reset() {
	*x = SendBtnGroupResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mixinsrv_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBtnGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBtnGroupResp) ProtoMessage() {}

func (x *SendBtnGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_mixinsrv_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBtnGroupResp.ProtoReflect.Descriptor instead.
func (*SendBtnGroupResp) Descriptor() ([]byte, []int) {
	return file_mixinsrv_proto_rawDescGZIP(), []int{7}
}

var File_mixinsrv_proto protoreflect.FileDescriptor

var file_mixinsrv_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x69, 0x78, 0x69, 0x6e, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x79, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x70, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x70,
	0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d,
	0x65, 0x6d, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x22,
	0x12, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x49, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x49, 0x64, 0x22, 0x11,
	0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x85, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x74, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74,
	0x72, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x12,
	0x19, 0x0a, 0x08, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x69, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x49, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x65, 0x6e,
	0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x5d, 0x0a, 0x0f, 0x53, 0x65, 0x6e,
	0x64, 0x42, 0x74, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x49, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64,
	0x42, 0x74, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x32, 0xe7, 0x01, 0x0a,
	0x08, 0x6d, 0x69, 0x78, 0x69, 0x6e, 0x73, 0x72, 0x76, 0x12, 0x39, 0x0a, 0x0c, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x14,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64,
	0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x0c, 0x53,
	0x65, 0x6e, 0x64, 0x42, 0x74, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x74, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x74, 0x6e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mixinsrv_proto_rawDescOnce sync.Once
	file_mixinsrv_proto_rawDescData = file_mixinsrv_proto_rawDesc
)

func file_mixinsrv_proto_rawDescGZIP() []byte {
	file_mixinsrv_proto_rawDescOnce.Do(func() {
		file_mixinsrv_proto_rawDescData = protoimpl.X.CompressGZIP(file_mixinsrv_proto_rawDescData)
	})
	return file_mixinsrv_proto_rawDescData
}

var file_mixinsrv_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mixinsrv_proto_goTypes = []interface{}{
	(*SendTransferReq)(nil),  // 0: pb.SendTransferReq
	(*SendTransferResp)(nil), // 1: pb.SendTransferResp
	(*SendMessageReq)(nil),   // 2: pb.SendMessageReq
	(*SendMessageResp)(nil),  // 3: pb.SendMessageResp
	(*SendCardReq)(nil),      // 4: pb.SendCardReq
	(*SendCardResp)(nil),     // 5: pb.SendCardResp
	(*SendBtnGroupReq)(nil),  // 6: pb.SendBtnGroupReq
	(*SendBtnGroupResp)(nil), // 7: pb.SendBtnGroupResp
}
var file_mixinsrv_proto_depIdxs = []int32{
	0, // 0: pb.mixinsrv.SendTransfer:input_type -> pb.SendTransferReq
	4, // 1: pb.mixinsrv.SendCard:input_type -> pb.SendCardReq
	2, // 2: pb.mixinsrv.SendMessage:input_type -> pb.SendMessageReq
	6, // 3: pb.mixinsrv.SendBtnGroup:input_type -> pb.SendBtnGroupReq
	1, // 4: pb.mixinsrv.SendTransfer:output_type -> pb.SendTransferResp
	5, // 5: pb.mixinsrv.SendCard:output_type -> pb.SendCardResp
	3, // 6: pb.mixinsrv.SendMessage:output_type -> pb.SendMessageResp
	7, // 7: pb.mixinsrv.SendBtnGroup:output_type -> pb.SendBtnGroupResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mixinsrv_proto_init() }
func file_mixinsrv_proto_init() {
	if File_mixinsrv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mixinsrv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTransferReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mixinsrv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTransferResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mixinsrv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mixinsrv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mixinsrv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mixinsrv_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mixinsrv_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBtnGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mixinsrv_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBtnGroupResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mixinsrv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mixinsrv_proto_goTypes,
		DependencyIndexes: file_mixinsrv_proto_depIdxs,
		MessageInfos:      file_mixinsrv_proto_msgTypes,
	}.Build()
	File_mixinsrv_proto = out.File
	file_mixinsrv_proto_rawDesc = nil
	file_mixinsrv_proto_goTypes = nil
	file_mixinsrv_proto_depIdxs = nil
}
